

services:
  # 1. The Database Vault
  postgres:
    image: postgres:15
    container_name: ccis_postgres_v1
    restart: always # Automatically restarts if the server crashes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: smartroom
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Visual Interface for your Database
  pgadmin:
    image: dpage/pgadmin4
    container_name: ccis_pgadmin_v1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres

volumes:
  postgres_data: